start transaction;
select * from t_binlog;
commit;
start transaction;
select * from t_binlog;
commit;
start transaction;
select * from t_binlog;
commit;
start transaction;
select * from my_hash;
commit;
start transaction;
select * from my_hash;
commit;
start transaction;
select * from my_hash;
select * from t_binlog;
commit;
